node1.detbrief.rrr.bf
*node2.detbrief.rrr.bf
**node4.detbrief.rrr.bf
***node8.detbrief.rrr.bf
****node16.detbrief.rrr.bf
*****node32.detbrief.rrr.bf
******node64.detbrief.rrr.bf
*******node128.detbrief.rrr.bf
********node256.detbrief.rrr.bf
*********node512.detbrief.rrr.bf
**********138.detbrief.rrr.bf
**********139.detbrief.rrr.bf
*********node513.detbrief.rrr.bf
**********14.detbrief.rrr.bf
**********140.detbrief.rrr.bf
********node257.detbrief.rrr.bf
*********node514.detbrief.rrr.bf
**********141.detbrief.rrr.bf
**********142.detbrief.rrr.bf
*********node515.detbrief.rrr.bf
**********143.detbrief.rrr.bf
**********144.detbrief.rrr.bf
*******node129.detbrief.rrr.bf
********node258.detbrief.rrr.bf
*********node516.detbrief.rrr.bf
**********145.detbrief.rrr.bf
**********146.detbrief.rrr.bf
*********node517.detbrief.rrr.bf
**********147.detbrief.rrr.bf
**********148.detbrief.rrr.bf
********node259.detbrief.rrr.bf
*********node518.detbrief.rrr.bf
**********149.detbrief.rrr.bf
**********15.detbrief.rrr.bf
*********node519.detbrief.rrr.bf
**********150.detbrief.rrr.bf
**********151.detbrief.rrr.bf
******node65.detbrief.rrr.bf
*******node130.detbrief.rrr.bf
********node260.detbrief.rrr.bf
*********node520.detbrief.rrr.bf
**********152.detbrief.rrr.bf
**********153.detbrief.rrr.bf
*********node521.detbrief.rrr.bf
**********154.detbrief.rrr.bf
**********155.detbrief.rrr.bf
********node261.detbrief.rrr.bf
*********node522.detbrief.rrr.bf
**********156.detbrief.rrr.bf
**********157.detbrief.rrr.bf
*********node523.detbrief.rrr.bf
**********158.detbrief.rrr.bf
**********159.detbrief.rrr.bf
*******node131.detbrief.rrr.bf
********node262.detbrief.rrr.bf
*********node524.detbrief.rrr.bf
**********16.detbrief.rrr.bf
**********160.detbrief.rrr.bf
*********node525.detbrief.rrr.bf
**********161.detbrief.rrr.bf
**********162.detbrief.rrr.bf
********node263.detbrief.rrr.bf
*********node526.detbrief.rrr.bf
**********163.detbrief.rrr.bf
**********164.detbrief.rrr.bf
*********node527.detbrief.rrr.bf
**********165.detbrief.rrr.bf
**********166.detbrief.rrr.bf
*****node33.detbrief.rrr.bf
******node66.detbrief.rrr.bf
*******node132.detbrief.rrr.bf
********node264.detbrief.rrr.bf
*********node528.detbrief.rrr.bf
**********167.detbrief.rrr.bf
**********168.detbrief.rrr.bf
*********node529.detbrief.rrr.bf
**********169.detbrief.rrr.bf
**********17.detbrief.rrr.bf
********node265.detbrief.rrr.bf
*********node530.detbrief.rrr.bf
**********170.detbrief.rrr.bf
**********171.detbrief.rrr.bf
*********node531.detbrief.rrr.bf
**********172.detbrief.rrr.bf
**********173.detbrief.rrr.bf
*******node133.detbrief.rrr.bf
********node266.detbrief.rrr.bf
*********node532.detbrief.rrr.bf
**********174.detbrief.rrr.bf
**********175.detbrief.rrr.bf
*********node533.detbrief.rrr.bf
**********176.detbrief.rrr.bf
**********177.detbrief.rrr.bf
********node267.detbrief.rrr.bf
*********node534.detbrief.rrr.bf
**********178.detbrief.rrr.bf
**********179.detbrief.rrr.bf
*********node535.detbrief.rrr.bf
**********18.detbrief.rrr.bf
**********180.detbrief.rrr.bf
******node67.detbrief.rrr.bf
*******node134.detbrief.rrr.bf
********node268.detbrief.rrr.bf
*********node536.detbrief.rrr.bf
**********181.detbrief.rrr.bf
**********182.detbrief.rrr.bf
*********node537.detbrief.rrr.bf
**********183.detbrief.rrr.bf
**********184.detbrief.rrr.bf
********node269.detbrief.rrr.bf
*********node538.detbrief.rrr.bf
**********185.detbrief.rrr.bf
**********186.detbrief.rrr.bf
*********node539.detbrief.rrr.bf
**********187.detbrief.rrr.bf
**********188.detbrief.rrr.bf
*******node135.detbrief.rrr.bf
********node270.detbrief.rrr.bf
*********node540.detbrief.rrr.bf
**********189.detbrief.rrr.bf
**********19.detbrief.rrr.bf
*********node541.detbrief.rrr.bf
**********190.detbrief.rrr.bf
**********191.detbrief.rrr.bf
********node271.detbrief.rrr.bf
*********node542.detbrief.rrr.bf
**********192.detbrief.rrr.bf
**********193.detbrief.rrr.bf
*********node543.detbrief.rrr.bf
**********194.detbrief.rrr.bf
**********195.detbrief.rrr.bf
****node17.detbrief.rrr.bf
*****node34.detbrief.rrr.bf
******node68.detbrief.rrr.bf
*******node136.detbrief.rrr.bf
********node272.detbrief.rrr.bf
*********node544.detbrief.rrr.bf
**********196.detbrief.rrr.bf
**********197.detbrief.rrr.bf
*********node545.detbrief.rrr.bf
**********198.detbrief.rrr.bf
**********199.detbrief.rrr.bf
********node273.detbrief.rrr.bf
*********node546.detbrief.rrr.bf
**********2.detbrief.rrr.bf
**********20.detbrief.rrr.bf
*********node547.detbrief.rrr.bf
**********200.detbrief.rrr.bf
**********201.detbrief.rrr.bf
*******node137.detbrief.rrr.bf
********node274.detbrief.rrr.bf
*********node548.detbrief.rrr.bf
**********202.detbrief.rrr.bf
**********203.detbrief.rrr.bf
*********node549.detbrief.rrr.bf
**********204.detbrief.rrr.bf
**********205.detbrief.rrr.bf
********node275.detbrief.rrr.bf
*********node550.detbrief.rrr.bf
**********206.detbrief.rrr.bf
**********207.detbrief.rrr.bf
*********node551.detbrief.rrr.bf
**********208.detbrief.rrr.bf
**********209.detbrief.rrr.bf
******node69.detbrief.rrr.bf
*******node138.detbrief.rrr.bf
********node276.detbrief.rrr.bf
*********node552.detbrief.rrr.bf
**********21.detbrief.rrr.bf
**********210.detbrief.rrr.bf
*********node553.detbrief.rrr.bf
**********211.detbrief.rrr.bf
**********212.detbrief.rrr.bf
********node277.detbrief.rrr.bf
*********node554.detbrief.rrr.bf
**********213.detbrief.rrr.bf
**********214.detbrief.rrr.bf
*********node555.detbrief.rrr.bf
**********215.detbrief.rrr.bf
**********216.detbrief.rrr.bf
*******node139.detbrief.rrr.bf
********node278.detbrief.rrr.bf
*********node556.detbrief.rrr.bf
**********217.detbrief.rrr.bf
**********218.detbrief.rrr.bf
*********node557.detbrief.rrr.bf
**********219.detbrief.rrr.bf
**********22.detbrief.rrr.bf
********node279.detbrief.rrr.bf
*********node558.detbrief.rrr.bf
**********220.detbrief.rrr.bf
**********221.detbrief.rrr.bf
*********node559.detbrief.rrr.bf
**********222.detbrief.rrr.bf
**********223.detbrief.rrr.bf
*****node35.detbrief.rrr.bf
******node70.detbrief.rrr.bf
*******node140.detbrief.rrr.bf
********node280.detbrief.rrr.bf
*********node560.detbrief.rrr.bf
**********224.detbrief.rrr.bf
**********225.detbrief.rrr.bf
*********node561.detbrief.rrr.bf
**********226.detbrief.rrr.bf
**********227.detbrief.rrr.bf
********node281.detbrief.rrr.bf
*********node562.detbrief.rrr.bf
**********228.detbrief.rrr.bf
**********229.detbrief.rrr.bf
*********node563.detbrief.rrr.bf
**********23.detbrief.rrr.bf
**********230.detbrief.rrr.bf
*******node141.detbrief.rrr.bf
********node282.detbrief.rrr.bf
*********node564.detbrief.rrr.bf
**********231.detbrief.rrr.bf
**********232.detbrief.rrr.bf
*********node565.detbrief.rrr.bf
**********233.detbrief.rrr.bf
**********234.detbrief.rrr.bf
********node283.detbrief.rrr.bf
*********node566.detbrief.rrr.bf
**********235.detbrief.rrr.bf
**********236.detbrief.rrr.bf
*********node567.detbrief.rrr.bf
**********237.detbrief.rrr.bf
**********238.detbrief.rrr.bf
******node71.detbrief.rrr.bf
*******node142.detbrief.rrr.bf
********node284.detbrief.rrr.bf
*********node568.detbrief.rrr.bf
**********239.detbrief.rrr.bf
**********24.detbrief.rrr.bf
*********node569.detbrief.rrr.bf
**********240.detbrief.rrr.bf
**********241.detbrief.rrr.bf
********node285.detbrief.rrr.bf
*********node570.detbrief.rrr.bf
**********242.detbrief.rrr.bf
**********243.detbrief.rrr.bf
*********node571.detbrief.rrr.bf
**********244.detbrief.rrr.bf
**********245.detbrief.rrr.bf
*******node143.detbrief.rrr.bf
********node286.detbrief.rrr.bf
*********node572.detbrief.rrr.bf
**********246.detbrief.rrr.bf
**********247.detbrief.rrr.bf
*********node573.detbrief.rrr.bf
**********248.detbrief.rrr.bf
**********249.detbrief.rrr.bf
********node287.detbrief.rrr.bf
*********node574.detbrief.rrr.bf
**********25.detbrief.rrr.bf
**********250.detbrief.rrr.bf
*********node575.detbrief.rrr.bf
**********251.detbrief.rrr.bf
**********252.detbrief.rrr.bf
***node9.detbrief.rrr.bf
****node18.detbrief.rrr.bf
*****node36.detbrief.rrr.bf
******node72.detbrief.rrr.bf
*******node144.detbrief.rrr.bf
********node288.detbrief.rrr.bf
*********node576.detbrief.rrr.bf
**********253.detbrief.rrr.bf
**********254.detbrief.rrr.bf
*********node577.detbrief.rrr.bf
**********255.detbrief.rrr.bf
**********256.detbrief.rrr.bf
********node289.detbrief.rrr.bf
*********node578.detbrief.rrr.bf
**********257.detbrief.rrr.bf
**********258.detbrief.rrr.bf
*********node579.detbrief.rrr.bf
**********259.detbrief.rrr.bf
**********26.detbrief.rrr.bf
*******node145.detbrief.rrr.bf
********node290.detbrief.rrr.bf
*********node580.detbrief.rrr.bf
**********260.detbrief.rrr.bf
**********261.detbrief.rrr.bf
*********node581.detbrief.rrr.bf
**********262.detbrief.rrr.bf
**********263.detbrief.rrr.bf
********node291.detbrief.rrr.bf
*********node582.detbrief.rrr.bf
**********264.detbrief.rrr.bf
**********265.detbrief.rrr.bf
*********node583.detbrief.rrr.bf
**********266.detbrief.rrr.bf
**********267.detbrief.rrr.bf
******node73.detbrief.rrr.bf
*******node146.detbrief.rrr.bf
********node292.detbrief.rrr.bf
*********node584.detbrief.rrr.bf
**********268.detbrief.rrr.bf
**********269.detbrief.rrr.bf
*********node585.detbrief.rrr.bf
**********27.detbrief.rrr.bf
**********270.detbrief.rrr.bf
********node293.detbrief.rrr.bf
*********node586.detbrief.rrr.bf
**********271.detbrief.rrr.bf
**********272.detbrief.rrr.bf
*********node587.detbrief.rrr.bf
**********273.detbrief.rrr.bf
**********274.detbrief.rrr.bf
*******node147.detbrief.rrr.bf
********node294.detbrief.rrr.bf
*********node588.detbrief.rrr.bf
**********275.detbrief.rrr.bf
**********276.detbrief.rrr.bf
*********node589.detbrief.rrr.bf
**********277.detbrief.rrr.bf
**********278.detbrief.rrr.bf
********node295.detbrief.rrr.bf
*********node590.detbrief.rrr.bf
**********279.detbrief.rrr.bf
**********28.detbrief.rrr.bf
*********node591.detbrief.rrr.bf
**********280.detbrief.rrr.bf
**********281.detbrief.rrr.bf
*****node37.detbrief.rrr.bf
******node74.detbrief.rrr.bf
*******node148.detbrief.rrr.bf
********node296.detbrief.rrr.bf
*********node592.detbrief.rrr.bf
**********282.detbrief.rrr.bf
**********283.detbrief.rrr.bf
*********node593.detbrief.rrr.bf
**********284.detbrief.rrr.bf
**********285.detbrief.rrr.bf
********node297.detbrief.rrr.bf
*********node594.detbrief.rrr.bf
**********286.detbrief.rrr.bf
**********287.detbrief.rrr.bf
*********node595.detbrief.rrr.bf
**********288.detbrief.rrr.bf
**********289.detbrief.rrr.bf
*******node149.detbrief.rrr.bf
********node298.detbrief.rrr.bf
*********node596.detbrief.rrr.bf
**********29.detbrief.rrr.bf
**********290.detbrief.rrr.bf
*********node597.detbrief.rrr.bf
**********291.detbrief.rrr.bf
**********292.detbrief.rrr.bf
********node299.detbrief.rrr.bf
*********node598.detbrief.rrr.bf
**********293.detbrief.rrr.bf
**********294.detbrief.rrr.bf
*********node599.detbrief.rrr.bf
**********295.detbrief.rrr.bf
**********296.detbrief.rrr.bf
******node75.detbrief.rrr.bf
*******node150.detbrief.rrr.bf
********node300.detbrief.rrr.bf
*********node600.detbrief.rrr.bf
**********297.detbrief.rrr.bf
**********298.detbrief.rrr.bf
*********node601.detbrief.rrr.bf
**********299.detbrief.rrr.bf
**********3.detbrief.rrr.bf
********node301.detbrief.rrr.bf
*********node602.detbrief.rrr.bf
**********30.detbrief.rrr.bf
**********300.detbrief.rrr.bf
*********node603.detbrief.rrr.bf
**********301.detbrief.rrr.bf
**********302.detbrief.rrr.bf
*******node151.detbrief.rrr.bf
********node302.detbrief.rrr.bf
*********node604.detbrief.rrr.bf
**********303.detbrief.rrr.bf
**********304.detbrief.rrr.bf
*********node605.detbrief.rrr.bf
**********305.detbrief.rrr.bf
**********306.detbrief.rrr.bf
********node303.detbrief.rrr.bf
*********node606.detbrief.rrr.bf
**********307.detbrief.rrr.bf
**********308.detbrief.rrr.bf
*********node607.detbrief.rrr.bf
**********309.detbrief.rrr.bf
**********31.detbrief.rrr.bf
****node19.detbrief.rrr.bf
*****node38.detbrief.rrr.bf
******node76.detbrief.rrr.bf
*******node152.detbrief.rrr.bf
********node304.detbrief.rrr.bf
*********node608.detbrief.rrr.bf
**********310.detbrief.rrr.bf
**********311.detbrief.rrr.bf
*********node609.detbrief.rrr.bf
**********312.detbrief.rrr.bf
**********313.detbrief.rrr.bf
********node305.detbrief.rrr.bf
*********node610.detbrief.rrr.bf
**********314.detbrief.rrr.bf
**********315.detbrief.rrr.bf
*********node611.detbrief.rrr.bf
**********316.detbrief.rrr.bf
**********317.detbrief.rrr.bf
*******node153.detbrief.rrr.bf
********node306.detbrief.rrr.bf
*********node612.detbrief.rrr.bf
**********318.detbrief.rrr.bf
**********319.detbrief.rrr.bf
*********node613.detbrief.rrr.bf
**********32.detbrief.rrr.bf
**********320.detbrief.rrr.bf
********node307.detbrief.rrr.bf
*********node614.detbrief.rrr.bf
**********321.detbrief.rrr.bf
**********322.detbrief.rrr.bf
*********node615.detbrief.rrr.bf
**********323.detbrief.rrr.bf
**********324.detbrief.rrr.bf
******node77.detbrief.rrr.bf
*******node154.detbrief.rrr.bf
********node308.detbrief.rrr.bf
*********node616.detbrief.rrr.bf
**********325.detbrief.rrr.bf
**********326.detbrief.rrr.bf
*********node617.detbrief.rrr.bf
**********327.detbrief.rrr.bf
**********328.detbrief.rrr.bf
********node309.detbrief.rrr.bf
*********node618.detbrief.rrr.bf
**********329.detbrief.rrr.bf
**********33.detbrief.rrr.bf
*********node619.detbrief.rrr.bf
**********330.detbrief.rrr.bf
**********331.detbrief.rrr.bf
*******node155.detbrief.rrr.bf
********node310.detbrief.rrr.bf
*********node620.detbrief.rrr.bf
**********332.detbrief.rrr.bf
**********333.detbrief.rrr.bf
*********node621.detbrief.rrr.bf
**********334.detbrief.rrr.bf
**********335.detbrief.rrr.bf
********node311.detbrief.rrr.bf
*********node622.detbrief.rrr.bf
**********336.detbrief.rrr.bf
**********337.detbrief.rrr.bf
*********node623.detbrief.rrr.bf
**********338.detbrief.rrr.bf
**********339.detbrief.rrr.bf
*****node39.detbrief.rrr.bf
******node78.detbrief.rrr.bf
*******node156.detbrief.rrr.bf
********node312.detbrief.rrr.bf
*********node624.detbrief.rrr.bf
**********34.detbrief.rrr.bf
**********340.detbrief.rrr.bf
*********node625.detbrief.rrr.bf
**********341.detbrief.rrr.bf
**********342.detbrief.rrr.bf
********node313.detbrief.rrr.bf
*********node626.detbrief.rrr.bf
**********343.detbrief.rrr.bf
**********344.detbrief.rrr.bf
*********node627.detbrief.rrr.bf
**********345.detbrief.rrr.bf
**********346.detbrief.rrr.bf
*******node157.detbrief.rrr.bf
********node314.detbrief.rrr.bf
*********node628.detbrief.rrr.bf
**********347.detbrief.rrr.bf
**********348.detbrief.rrr.bf
*********node629.detbrief.rrr.bf
**********349.detbrief.rrr.bf
**********35.detbrief.rrr.bf
********node315.detbrief.rrr.bf
*********node630.detbrief.rrr.bf
**********350.detbrief.rrr.bf
**********351.detbrief.rrr.bf
*********node631.detbrief.rrr.bf
**********352.detbrief.rrr.bf
**********353.detbrief.rrr.bf
******node79.detbrief.rrr.bf
*******node158.detbrief.rrr.bf
********node316.detbrief.rrr.bf
*********node632.detbrief.rrr.bf
**********354.detbrief.rrr.bf
**********355.detbrief.rrr.bf
*********node633.detbrief.rrr.bf
**********356.detbrief.rrr.bf
**********357.detbrief.rrr.bf
********node317.detbrief.rrr.bf
*********node634.detbrief.rrr.bf
**********358.detbrief.rrr.bf
**********359.detbrief.rrr.bf
*********node635.detbrief.rrr.bf
**********36.detbrief.rrr.bf
**********360.detbrief.rrr.bf
*******node159.detbrief.rrr.bf
********node318.detbrief.rrr.bf
*********node636.detbrief.rrr.bf
**********361.detbrief.rrr.bf
**********362.detbrief.rrr.bf
*********node637.detbrief.rrr.bf
**********363.detbrief.rrr.bf
**********364.detbrief.rrr.bf
********node319.detbrief.rrr.bf
*********node638.detbrief.rrr.bf
**********365.detbrief.rrr.bf
**********366.detbrief.rrr.bf
*********node639.detbrief.rrr.bf
**********367.detbrief.rrr.bf
**********368.detbrief.rrr.bf
**node5.detbrief.rrr.bf
***node10.detbrief.rrr.bf
****node20.detbrief.rrr.bf
*****node40.detbrief.rrr.bf
******node80.detbrief.rrr.bf
*******node160.detbrief.rrr.bf
********node320.detbrief.rrr.bf
*********node640.detbrief.rrr.bf
**********369.detbrief.rrr.bf
**********37.detbrief.rrr.bf
*********node641.detbrief.rrr.bf
**********370.detbrief.rrr.bf
**********371.detbrief.rrr.bf
********node321.detbrief.rrr.bf
*********node642.detbrief.rrr.bf
**********372.detbrief.rrr.bf
**********373.detbrief.rrr.bf
*********node643.detbrief.rrr.bf
**********374.detbrief.rrr.bf
**********375.detbrief.rrr.bf
*******node161.detbrief.rrr.bf
********node322.detbrief.rrr.bf
*********node644.detbrief.rrr.bf
**********376.detbrief.rrr.bf
**********377.detbrief.rrr.bf
*********node645.detbrief.rrr.bf
**********378.detbrief.rrr.bf
**********379.detbrief.rrr.bf
********node323.detbrief.rrr.bf
*********node646.detbrief.rrr.bf
**********38.detbrief.rrr.bf
**********380.detbrief.rrr.bf
*********node647.detbrief.rrr.bf
**********381.detbrief.rrr.bf
**********382.detbrief.rrr.bf
******node81.detbrief.rrr.bf
*******node162.detbrief.rrr.bf
********node324.detbrief.rrr.bf
*********node648.detbrief.rrr.bf
**********383.detbrief.rrr.bf
**********384.detbrief.rrr.bf
*********node649.detbrief.rrr.bf
**********385.detbrief.rrr.bf
**********386.detbrief.rrr.bf
********node325.detbrief.rrr.bf
*********node650.detbrief.rrr.bf
**********387.detbrief.rrr.bf
**********388.detbrief.rrr.bf
*********node651.detbrief.rrr.bf
**********389.detbrief.rrr.bf
**********39.detbrief.rrr.bf
*******node163.detbrief.rrr.bf
********node326.detbrief.rrr.bf
*********node652.detbrief.rrr.bf
**********390.detbrief.rrr.bf
**********391.detbrief.rrr.bf
*********node653.detbrief.rrr.bf
**********392.detbrief.rrr.bf
**********393.detbrief.rrr.bf
********node327.detbrief.rrr.bf
*********node654.detbrief.rrr.bf
**********394.detbrief.rrr.bf
**********395.detbrief.rrr.bf
*********node655.detbrief.rrr.bf
**********396.detbrief.rrr.bf
**********397.detbrief.rrr.bf
*****node41.detbrief.rrr.bf
******node82.detbrief.rrr.bf
*******node164.detbrief.rrr.bf
********node328.detbrief.rrr.bf
*********node656.detbrief.rrr.bf
**********398.detbrief.rrr.bf
**********399.detbrief.rrr.bf
*********node657.detbrief.rrr.bf
**********4.detbrief.rrr.bf
**********40.detbrief.rrr.bf
********node329.detbrief.rrr.bf
*********node658.detbrief.rrr.bf
**********400.detbrief.rrr.bf
**********401.detbrief.rrr.bf
*********node659.detbrief.rrr.bf
**********402.detbrief.rrr.bf
**********403.detbrief.rrr.bf
*******node165.detbrief.rrr.bf
********node330.detbrief.rrr.bf
*********node660.detbrief.rrr.bf
**********404.detbrief.rrr.bf
**********405.detbrief.rrr.bf
*********node661.detbrief.rrr.bf
**********406.detbrief.rrr.bf
**********407.detbrief.rrr.bf
********node331.detbrief.rrr.bf
*********node662.detbrief.rrr.bf
**********408.detbrief.rrr.bf
**********409.detbrief.rrr.bf
*********node663.detbrief.rrr.bf
**********41.detbrief.rrr.bf
**********410.detbrief.rrr.bf
******node83.detbrief.rrr.bf
*******node166.detbrief.rrr.bf
********node332.detbrief.rrr.bf
*********node664.detbrief.rrr.bf
**********411.detbrief.rrr.bf
**********412.detbrief.rrr.bf
*********node665.detbrief.rrr.bf
**********413.detbrief.rrr.bf
**********414.detbrief.rrr.bf
********node333.detbrief.rrr.bf
*********node666.detbrief.rrr.bf
**********415.detbrief.rrr.bf
**********416.detbrief.rrr.bf
*********node667.detbrief.rrr.bf
**********417.detbrief.rrr.bf
**********418.detbrief.rrr.bf
*******node167.detbrief.rrr.bf
********node334.detbrief.rrr.bf
*********node668.detbrief.rrr.bf
**********419.detbrief.rrr.bf
**********42.detbrief.rrr.bf
*********node669.detbrief.rrr.bf
**********420.detbrief.rrr.bf
**********421.detbrief.rrr.bf
********node335.detbrief.rrr.bf
*********node670.detbrief.rrr.bf
**********422.detbrief.rrr.bf
**********423.detbrief.rrr.bf
*********node671.detbrief.rrr.bf
**********424.detbrief.rrr.bf
**********425.detbrief.rrr.bf
****node21.detbrief.rrr.bf
*****node42.detbrief.rrr.bf
******node84.detbrief.rrr.bf
*******node168.detbrief.rrr.bf
********node336.detbrief.rrr.bf
*********node672.detbrief.rrr.bf
**********426.detbrief.rrr.bf
**********427.detbrief.rrr.bf
*********node673.detbrief.rrr.bf
**********428.detbrief.rrr.bf
**********429.detbrief.rrr.bf
********node337.detbrief.rrr.bf
*********node674.detbrief.rrr.bf
**********43.detbrief.rrr.bf
**********430.detbrief.rrr.bf
*********node675.detbrief.rrr.bf
**********431.detbrief.rrr.bf
**********432.detbrief.rrr.bf
*******node169.detbrief.rrr.bf
********node338.detbrief.rrr.bf
*********node676.detbrief.rrr.bf
**********433.detbrief.rrr.bf
**********434.detbrief.rrr.bf
*********node677.detbrief.rrr.bf
**********435.detbrief.rrr.bf
**********436.detbrief.rrr.bf
********node339.detbrief.rrr.bf
*********node678.detbrief.rrr.bf
**********437.detbrief.rrr.bf
**********438.detbrief.rrr.bf
*********node679.detbrief.rrr.bf
**********439.detbrief.rrr.bf
**********44.detbrief.rrr.bf
******node85.detbrief.rrr.bf
*******node170.detbrief.rrr.bf
********node340.detbrief.rrr.bf
*********node680.detbrief.rrr.bf
**********440.detbrief.rrr.bf
**********441.detbrief.rrr.bf
*********node681.detbrief.rrr.bf
**********442.detbrief.rrr.bf
**********443.detbrief.rrr.bf
********node341.detbrief.rrr.bf
*********node682.detbrief.rrr.bf
**********444.detbrief.rrr.bf
**********445.detbrief.rrr.bf
*********node683.detbrief.rrr.bf
**********446.detbrief.rrr.bf
**********447.detbrief.rrr.bf
*******node171.detbrief.rrr.bf
********node342.detbrief.rrr.bf
*********node684.detbrief.rrr.bf
**********448.detbrief.rrr.bf
**********449.detbrief.rrr.bf
*********node685.detbrief.rrr.bf
**********45.detbrief.rrr.bf
**********450.detbrief.rrr.bf
********node343.detbrief.rrr.bf
*********node686.detbrief.rrr.bf
**********451.detbrief.rrr.bf
**********452.detbrief.rrr.bf
*********node687.detbrief.rrr.bf
**********453.detbrief.rrr.bf
**********454.detbrief.rrr.bf
*****node43.detbrief.rrr.bf
******node86.detbrief.rrr.bf
*******node172.detbrief.rrr.bf
********node344.detbrief.rrr.bf
*********node688.detbrief.rrr.bf
**********455.detbrief.rrr.bf
**********456.detbrief.rrr.bf
*********node689.detbrief.rrr.bf
**********457.detbrief.rrr.bf
**********458.detbrief.rrr.bf
********node345.detbrief.rrr.bf
*********node690.detbrief.rrr.bf
**********459.detbrief.rrr.bf
**********46.detbrief.rrr.bf
*********node691.detbrief.rrr.bf
**********460.detbrief.rrr.bf
**********461.detbrief.rrr.bf
*******node173.detbrief.rrr.bf
********node346.detbrief.rrr.bf
*********node692.detbrief.rrr.bf
**********462.detbrief.rrr.bf
**********463.detbrief.rrr.bf
*********node693.detbrief.rrr.bf
**********464.detbrief.rrr.bf
**********465.detbrief.rrr.bf
********node347.detbrief.rrr.bf
*********node694.detbrief.rrr.bf
**********466.detbrief.rrr.bf
**********467.detbrief.rrr.bf
*********node695.detbrief.rrr.bf
**********468.detbrief.rrr.bf
**********469.detbrief.rrr.bf
******node87.detbrief.rrr.bf
*******node174.detbrief.rrr.bf
********node348.detbrief.rrr.bf
*********node696.detbrief.rrr.bf
**********47.detbrief.rrr.bf
**********470.detbrief.rrr.bf
*********node697.detbrief.rrr.bf
**********471.detbrief.rrr.bf
**********472.detbrief.rrr.bf
********node349.detbrief.rrr.bf
*********node698.detbrief.rrr.bf
**********473.detbrief.rrr.bf
**********474.detbrief.rrr.bf
*********node699.detbrief.rrr.bf
**********475.detbrief.rrr.bf
**********476.detbrief.rrr.bf
*******node175.detbrief.rrr.bf
********node350.detbrief.rrr.bf
*********node700.detbrief.rrr.bf
**********477.detbrief.rrr.bf
**********478.detbrief.rrr.bf
*********node701.detbrief.rrr.bf
**********479.detbrief.rrr.bf
**********48.detbrief.rrr.bf
********node351.detbrief.rrr.bf
*********node702.detbrief.rrr.bf
**********480.detbrief.rrr.bf
**********481.detbrief.rrr.bf
*********node703.detbrief.rrr.bf
**********482.detbrief.rrr.bf
**********483.detbrief.rrr.bf
***node11.detbrief.rrr.bf
****node22.detbrief.rrr.bf
*****node44.detbrief.rrr.bf
******node88.detbrief.rrr.bf
*******node176.detbrief.rrr.bf
********node352.detbrief.rrr.bf
*********node704.detbrief.rrr.bf
**********484.detbrief.rrr.bf
**********485.detbrief.rrr.bf
*********node705.detbrief.rrr.bf
**********486.detbrief.rrr.bf
**********487.detbrief.rrr.bf
********node353.detbrief.rrr.bf
*********node706.detbrief.rrr.bf
**********488.detbrief.rrr.bf
**********489.detbrief.rrr.bf
*********node707.detbrief.rrr.bf
**********49.detbrief.rrr.bf
**********490.detbrief.rrr.bf
*******node177.detbrief.rrr.bf
********node354.detbrief.rrr.bf
*********node708.detbrief.rrr.bf
**********491.detbrief.rrr.bf
**********492.detbrief.rrr.bf
*********node709.detbrief.rrr.bf
**********493.detbrief.rrr.bf
**********494.detbrief.rrr.bf
********node355.detbrief.rrr.bf
*********node710.detbrief.rrr.bf
**********495.detbrief.rrr.bf
**********496.detbrief.rrr.bf
*********node711.detbrief.rrr.bf
**********497.detbrief.rrr.bf
**********498.detbrief.rrr.bf
******node89.detbrief.rrr.bf
*******node178.detbrief.rrr.bf
********node356.detbrief.rrr.bf
*********node712.detbrief.rrr.bf
**********499.detbrief.rrr.bf
**********5.detbrief.rrr.bf
*********node713.detbrief.rrr.bf
**********50.detbrief.rrr.bf
**********500.detbrief.rrr.bf
********node357.detbrief.rrr.bf
*********node714.detbrief.rrr.bf
**********501.detbrief.rrr.bf
**********502.detbrief.rrr.bf
*********node715.detbrief.rrr.bf
**********503.detbrief.rrr.bf
**********504.detbrief.rrr.bf
*******node179.detbrief.rrr.bf
********node358.detbrief.rrr.bf
*********node716.detbrief.rrr.bf
**********505.detbrief.rrr.bf
**********506.detbrief.rrr.bf
*********node717.detbrief.rrr.bf
**********507.detbrief.rrr.bf
**********508.detbrief.rrr.bf
********node359.detbrief.rrr.bf
*********node718.detbrief.rrr.bf
**********509.detbrief.rrr.bf
**********51.detbrief.rrr.bf
*********node719.detbrief.rrr.bf
**********510.detbrief.rrr.bf
**********511.detbrief.rrr.bf
*****node45.detbrief.rrr.bf
******node90.detbrief.rrr.bf
*******node180.detbrief.rrr.bf
********node360.detbrief.rrr.bf
*********node720.detbrief.rrr.bf
**********512.detbrief.rrr.bf
**********513.detbrief.rrr.bf
*********node721.detbrief.rrr.bf
**********514.detbrief.rrr.bf
**********515.detbrief.rrr.bf
********node361.detbrief.rrr.bf
*********node722.detbrief.rrr.bf
**********516.detbrief.rrr.bf
**********517.detbrief.rrr.bf
*********node723.detbrief.rrr.bf
**********518.detbrief.rrr.bf
**********519.detbrief.rrr.bf
*******node181.detbrief.rrr.bf
********node362.detbrief.rrr.bf
*********node724.detbrief.rrr.bf
**********52.detbrief.rrr.bf
**********520.detbrief.rrr.bf
*********node725.detbrief.rrr.bf
**********521.detbrief.rrr.bf
**********522.detbrief.rrr.bf
********node363.detbrief.rrr.bf
*********node726.detbrief.rrr.bf
**********523.detbrief.rrr.bf
**********524.detbrief.rrr.bf
*********node727.detbrief.rrr.bf
**********525.detbrief.rrr.bf
**********526.detbrief.rrr.bf
******node91.detbrief.rrr.bf
*******node182.detbrief.rrr.bf
********node364.detbrief.rrr.bf
*********node728.detbrief.rrr.bf
**********527.detbrief.rrr.bf
**********528.detbrief.rrr.bf
*********node729.detbrief.rrr.bf
**********529.detbrief.rrr.bf
**********53.detbrief.rrr.bf
********node365.detbrief.rrr.bf
*********node730.detbrief.rrr.bf
**********530.detbrief.rrr.bf
**********531.detbrief.rrr.bf
*********node731.detbrief.rrr.bf
**********532.detbrief.rrr.bf
**********533.detbrief.rrr.bf
*******node183.detbrief.rrr.bf
********node366.detbrief.rrr.bf
*********node732.detbrief.rrr.bf
**********534.detbrief.rrr.bf
**********535.detbrief.rrr.bf
*********node733.detbrief.rrr.bf
**********536.detbrief.rrr.bf
**********537.detbrief.rrr.bf
********node367.detbrief.rrr.bf
*********node734.detbrief.rrr.bf
**********538.detbrief.rrr.bf
**********539.detbrief.rrr.bf
*********node735.detbrief.rrr.bf
**********54.detbrief.rrr.bf
**********540.detbrief.rrr.bf
****node23.detbrief.rrr.bf
*****node46.detbrief.rrr.bf
******node92.detbrief.rrr.bf
*******node184.detbrief.rrr.bf
********node368.detbrief.rrr.bf
*********node736.detbrief.rrr.bf
**********541.detbrief.rrr.bf
**********542.detbrief.rrr.bf
*********node737.detbrief.rrr.bf
**********543.detbrief.rrr.bf
**********544.detbrief.rrr.bf
********node369.detbrief.rrr.bf
*********node738.detbrief.rrr.bf
**********545.detbrief.rrr.bf
**********546.detbrief.rrr.bf
*********node739.detbrief.rrr.bf
**********547.detbrief.rrr.bf
**********548.detbrief.rrr.bf
*******node185.detbrief.rrr.bf
********node370.detbrief.rrr.bf
*********node740.detbrief.rrr.bf
**********549.detbrief.rrr.bf
**********55.detbrief.rrr.bf
*********node741.detbrief.rrr.bf
**********550.detbrief.rrr.bf
**********551.detbrief.rrr.bf
********node371.detbrief.rrr.bf
*********node742.detbrief.rrr.bf
**********552.detbrief.rrr.bf
**********553.detbrief.rrr.bf
*********node743.detbrief.rrr.bf
**********554.detbrief.rrr.bf
**********555.detbrief.rrr.bf
******node93.detbrief.rrr.bf
*******node186.detbrief.rrr.bf
********node372.detbrief.rrr.bf
*********node744.detbrief.rrr.bf
**********556.detbrief.rrr.bf
**********557.detbrief.rrr.bf
*********node745.detbrief.rrr.bf
**********558.detbrief.rrr.bf
**********559.detbrief.rrr.bf
********node373.detbrief.rrr.bf
*********node746.detbrief.rrr.bf
**********56.detbrief.rrr.bf
**********560.detbrief.rrr.bf
*********node747.detbrief.rrr.bf
**********561.detbrief.rrr.bf
**********562.detbrief.rrr.bf
*******node187.detbrief.rrr.bf
********node374.detbrief.rrr.bf
*********node748.detbrief.rrr.bf
**********563.detbrief.rrr.bf
**********564.detbrief.rrr.bf
*********node749.detbrief.rrr.bf
**********565.detbrief.rrr.bf
**********566.detbrief.rrr.bf
********node375.detbrief.rrr.bf
*********node750.detbrief.rrr.bf
**********567.detbrief.rrr.bf
**********568.detbrief.rrr.bf
*********node751.detbrief.rrr.bf
**********569.detbrief.rrr.bf
**********57.detbrief.rrr.bf
*****node47.detbrief.rrr.bf
******node94.detbrief.rrr.bf
*******node188.detbrief.rrr.bf
********node376.detbrief.rrr.bf
*********node752.detbrief.rrr.bf
**********570.detbrief.rrr.bf
**********571.detbrief.rrr.bf
*********node753.detbrief.rrr.bf
**********572.detbrief.rrr.bf
**********573.detbrief.rrr.bf
********node377.detbrief.rrr.bf
*********node754.detbrief.rrr.bf
**********574.detbrief.rrr.bf
**********575.detbrief.rrr.bf
*********node755.detbrief.rrr.bf
**********576.detbrief.rrr.bf
**********577.detbrief.rrr.bf
*******node189.detbrief.rrr.bf
********node378.detbrief.rrr.bf
*********node756.detbrief.rrr.bf
**********578.detbrief.rrr.bf
**********579.detbrief.rrr.bf
*********node757.detbrief.rrr.bf
**********58.detbrief.rrr.bf
**********580.detbrief.rrr.bf
********node379.detbrief.rrr.bf
*********node758.detbrief.rrr.bf
**********581.detbrief.rrr.bf
**********582.detbrief.rrr.bf
*********node759.detbrief.rrr.bf
**********583.detbrief.rrr.bf
**********584.detbrief.rrr.bf
******node95.detbrief.rrr.bf
*******node190.detbrief.rrr.bf
********node380.detbrief.rrr.bf
*********node760.detbrief.rrr.bf
**********585.detbrief.rrr.bf
**********586.detbrief.rrr.bf
*********node761.detbrief.rrr.bf
**********587.detbrief.rrr.bf
**********588.detbrief.rrr.bf
********node381.detbrief.rrr.bf
*********node762.detbrief.rrr.bf
**********589.detbrief.rrr.bf
**********59.detbrief.rrr.bf
*********node763.detbrief.rrr.bf
**********590.detbrief.rrr.bf
**********591.detbrief.rrr.bf
*******node191.detbrief.rrr.bf
********node382.detbrief.rrr.bf
*********node764.detbrief.rrr.bf
**********592.detbrief.rrr.bf
**********593.detbrief.rrr.bf
*********node765.detbrief.rrr.bf
**********594.detbrief.rrr.bf
**********595.detbrief.rrr.bf
********node383.detbrief.rrr.bf
*********node766.detbrief.rrr.bf
**********596.detbrief.rrr.bf
**********597.detbrief.rrr.bf
*********node767.detbrief.rrr.bf
**********598.detbrief.rrr.bf
**********599.detbrief.rrr.bf
*node3.detbrief.rrr.bf
**node6.detbrief.rrr.bf
***node12.detbrief.rrr.bf
****node24.detbrief.rrr.bf
*****node48.detbrief.rrr.bf
******node96.detbrief.rrr.bf
*******node192.detbrief.rrr.bf
********node384.detbrief.rrr.bf
*********node768.detbrief.rrr.bf
**********6.detbrief.rrr.bf
**********60.detbrief.rrr.bf
*********node769.detbrief.rrr.bf
**********600.detbrief.rrr.bf
**********601.detbrief.rrr.bf
********node385.detbrief.rrr.bf
*********node770.detbrief.rrr.bf
**********602.detbrief.rrr.bf
**********603.detbrief.rrr.bf
*********node771.detbrief.rrr.bf
**********604.detbrief.rrr.bf
**********605.detbrief.rrr.bf
*******node193.detbrief.rrr.bf
********node386.detbrief.rrr.bf
*********node772.detbrief.rrr.bf
**********606.detbrief.rrr.bf
**********607.detbrief.rrr.bf
*********node773.detbrief.rrr.bf
**********608.detbrief.rrr.bf
**********609.detbrief.rrr.bf
********node387.detbrief.rrr.bf
*********node774.detbrief.rrr.bf
**********61.detbrief.rrr.bf
**********610.detbrief.rrr.bf
*********node775.detbrief.rrr.bf
**********611.detbrief.rrr.bf
**********612.detbrief.rrr.bf
******node97.detbrief.rrr.bf
*******node194.detbrief.rrr.bf
********node388.detbrief.rrr.bf
*********node776.detbrief.rrr.bf
**********613.detbrief.rrr.bf
**********614.detbrief.rrr.bf
*********node777.detbrief.rrr.bf
**********615.detbrief.rrr.bf
**********616.detbrief.rrr.bf
********node389.detbrief.rrr.bf
*********node778.detbrief.rrr.bf
**********617.detbrief.rrr.bf
**********618.detbrief.rrr.bf
*********node779.detbrief.rrr.bf
**********619.detbrief.rrr.bf
**********62.detbrief.rrr.bf
*******node195.detbrief.rrr.bf
********node390.detbrief.rrr.bf
*********node780.detbrief.rrr.bf
**********620.detbrief.rrr.bf
**********621.detbrief.rrr.bf
*********node781.detbrief.rrr.bf
**********622.detbrief.rrr.bf
**********623.detbrief.rrr.bf
********node391.detbrief.rrr.bf
*********node782.detbrief.rrr.bf
**********624.detbrief.rrr.bf
**********625.detbrief.rrr.bf
*********node783.detbrief.rrr.bf
**********626.detbrief.rrr.bf
**********627.detbrief.rrr.bf
*****node49.detbrief.rrr.bf
******node98.detbrief.rrr.bf
*******node196.detbrief.rrr.bf
********node392.detbrief.rrr.bf
*********node784.detbrief.rrr.bf
**********628.detbrief.rrr.bf
**********629.detbrief.rrr.bf
*********node785.detbrief.rrr.bf
**********63.detbrief.rrr.bf
**********630.detbrief.rrr.bf
********node393.detbrief.rrr.bf
*********node786.detbrief.rrr.bf
**********631.detbrief.rrr.bf
**********632.detbrief.rrr.bf
*********node787.detbrief.rrr.bf
**********633.detbrief.rrr.bf
**********634.detbrief.rrr.bf
*******node197.detbrief.rrr.bf
********node394.detbrief.rrr.bf
*********node788.detbrief.rrr.bf
**********635.detbrief.rrr.bf
**********636.detbrief.rrr.bf
*********node789.detbrief.rrr.bf
**********637.detbrief.rrr.bf
**********638.detbrief.rrr.bf
********node395.detbrief.rrr.bf
*********node790.detbrief.rrr.bf
**********639.detbrief.rrr.bf
**********64.detbrief.rrr.bf
*********node791.detbrief.rrr.bf
**********640.detbrief.rrr.bf
**********641.detbrief.rrr.bf
******node99.detbrief.rrr.bf
*******node198.detbrief.rrr.bf
********node396.detbrief.rrr.bf
*********node792.detbrief.rrr.bf
**********642.detbrief.rrr.bf
**********643.detbrief.rrr.bf
*********node793.detbrief.rrr.bf
**********644.detbrief.rrr.bf
**********645.detbrief.rrr.bf
********node397.detbrief.rrr.bf
*********node794.detbrief.rrr.bf
**********646.detbrief.rrr.bf
**********647.detbrief.rrr.bf
*********node795.detbrief.rrr.bf
**********648.detbrief.rrr.bf
**********649.detbrief.rrr.bf
*******node199.detbrief.rrr.bf
********node398.detbrief.rrr.bf
*********node796.detbrief.rrr.bf
**********65.detbrief.rrr.bf
**********650.detbrief.rrr.bf
*********node797.detbrief.rrr.bf
**********651.detbrief.rrr.bf
**********652.detbrief.rrr.bf
********node399.detbrief.rrr.bf
*********node798.detbrief.rrr.bf
**********653.detbrief.rrr.bf
**********654.detbrief.rrr.bf
*********node799.detbrief.rrr.bf
**********655.detbrief.rrr.bf
**********656.detbrief.rrr.bf
****node25.detbrief.rrr.bf
*****node50.detbrief.rrr.bf
******node100.detbrief.rrr.bf
*******node200.detbrief.rrr.bf
********node400.detbrief.rrr.bf
*********node800.detbrief.rrr.bf
**********657.detbrief.rrr.bf
**********658.detbrief.rrr.bf
*********node801.detbrief.rrr.bf
**********659.detbrief.rrr.bf
**********66.detbrief.rrr.bf
********node401.detbrief.rrr.bf
*********node802.detbrief.rrr.bf
**********660.detbrief.rrr.bf
**********661.detbrief.rrr.bf
*********node803.detbrief.rrr.bf
**********662.detbrief.rrr.bf
**********663.detbrief.rrr.bf
*******node201.detbrief.rrr.bf
********node402.detbrief.rrr.bf
*********node804.detbrief.rrr.bf
**********664.detbrief.rrr.bf
**********665.detbrief.rrr.bf
*********node805.detbrief.rrr.bf
**********666.detbrief.rrr.bf
**********667.detbrief.rrr.bf
********node403.detbrief.rrr.bf
*********node806.detbrief.rrr.bf
**********668.detbrief.rrr.bf
**********669.detbrief.rrr.bf
*********node807.detbrief.rrr.bf
**********67.detbrief.rrr.bf
**********670.detbrief.rrr.bf
******node101.detbrief.rrr.bf
*******node202.detbrief.rrr.bf
********node404.detbrief.rrr.bf
*********node808.detbrief.rrr.bf
**********671.detbrief.rrr.bf
**********672.detbrief.rrr.bf
*********node809.detbrief.rrr.bf
**********673.detbrief.rrr.bf
**********674.detbrief.rrr.bf
********node405.detbrief.rrr.bf
*********node810.detbrief.rrr.bf
**********675.detbrief.rrr.bf
**********676.detbrief.rrr.bf
*********node811.detbrief.rrr.bf
**********677.detbrief.rrr.bf
**********678.detbrief.rrr.bf
*******node203.detbrief.rrr.bf
********node406.detbrief.rrr.bf
*********node812.detbrief.rrr.bf
**********679.detbrief.rrr.bf
**********68.detbrief.rrr.bf
*********node813.detbrief.rrr.bf
**********680.detbrief.rrr.bf
**********681.detbrief.rrr.bf
********node407.detbrief.rrr.bf
*********node814.detbrief.rrr.bf
**********682.detbrief.rrr.bf
**********683.detbrief.rrr.bf
*********node815.detbrief.rrr.bf
**********684.detbrief.rrr.bf
**********685.detbrief.rrr.bf
*****node51.detbrief.rrr.bf
******node102.detbrief.rrr.bf
*******node204.detbrief.rrr.bf
********node408.detbrief.rrr.bf
*********node816.detbrief.rrr.bf
**********686.detbrief.rrr.bf
**********687.detbrief.rrr.bf
*********node817.detbrief.rrr.bf
**********688.detbrief.rrr.bf
**********689.detbrief.rrr.bf
********node409.detbrief.rrr.bf
*********node818.detbrief.rrr.bf
**********69.detbrief.rrr.bf
**********690.detbrief.rrr.bf
*********node819.detbrief.rrr.bf
**********691.detbrief.rrr.bf
**********692.detbrief.rrr.bf
*******node205.detbrief.rrr.bf
********node410.detbrief.rrr.bf
*********node820.detbrief.rrr.bf
**********693.detbrief.rrr.bf
**********694.detbrief.rrr.bf
*********node821.detbrief.rrr.bf
**********695.detbrief.rrr.bf
**********696.detbrief.rrr.bf
********node411.detbrief.rrr.bf
*********node822.detbrief.rrr.bf
**********697.detbrief.rrr.bf
**********698.detbrief.rrr.bf
*********node823.detbrief.rrr.bf
**********699.detbrief.rrr.bf
**********7.detbrief.rrr.bf
******node103.detbrief.rrr.bf
*******node206.detbrief.rrr.bf
********node412.detbrief.rrr.bf
*********node824.detbrief.rrr.bf
**********70.detbrief.rrr.bf
**********700.detbrief.rrr.bf
*********node825.detbrief.rrr.bf
**********701.detbrief.rrr.bf
**********702.detbrief.rrr.bf
********node413.detbrief.rrr.bf
*********node826.detbrief.rrr.bf
**********703.detbrief.rrr.bf
**********704.detbrief.rrr.bf
*********node827.detbrief.rrr.bf
**********705.detbrief.rrr.bf
**********706.detbrief.rrr.bf
*******node207.detbrief.rrr.bf
********node414.detbrief.rrr.bf
*********node828.detbrief.rrr.bf
**********707.detbrief.rrr.bf
**********708.detbrief.rrr.bf
*********node829.detbrief.rrr.bf
**********709.detbrief.rrr.bf
**********71.detbrief.rrr.bf
********node415.detbrief.rrr.bf
*********node830.detbrief.rrr.bf
**********710.detbrief.rrr.bf
**********711.detbrief.rrr.bf
*********node831.detbrief.rrr.bf
**********712.detbrief.rrr.bf
**********713.detbrief.rrr.bf
***node13.detbrief.rrr.bf
****node26.detbrief.rrr.bf
*****node52.detbrief.rrr.bf
******node104.detbrief.rrr.bf
*******node208.detbrief.rrr.bf
********node416.detbrief.rrr.bf
*********node832.detbrief.rrr.bf
**********714.detbrief.rrr.bf
**********715.detbrief.rrr.bf
*********node833.detbrief.rrr.bf
**********716.detbrief.rrr.bf
**********717.detbrief.rrr.bf
********node417.detbrief.rrr.bf
*********node834.detbrief.rrr.bf
**********718.detbrief.rrr.bf
**********719.detbrief.rrr.bf
*********node835.detbrief.rrr.bf
**********72.detbrief.rrr.bf
**********720.detbrief.rrr.bf
*******node209.detbrief.rrr.bf
********node418.detbrief.rrr.bf
*********node836.detbrief.rrr.bf
**********721.detbrief.rrr.bf
**********722.detbrief.rrr.bf
*********node837.detbrief.rrr.bf
**********723.detbrief.rrr.bf
**********724.detbrief.rrr.bf
********node419.detbrief.rrr.bf
*********node838.detbrief.rrr.bf
**********725.detbrief.rrr.bf
**********726.detbrief.rrr.bf
*********node839.detbrief.rrr.bf
**********727.detbrief.rrr.bf
**********728.detbrief.rrr.bf
******node105.detbrief.rrr.bf
*******node210.detbrief.rrr.bf
********node420.detbrief.rrr.bf
*********node840.detbrief.rrr.bf
**********729.detbrief.rrr.bf
**********73.detbrief.rrr.bf
*********node841.detbrief.rrr.bf
**********730.detbrief.rrr.bf
**********731.detbrief.rrr.bf
********node421.detbrief.rrr.bf
*********node842.detbrief.rrr.bf
**********732.detbrief.rrr.bf
**********733.detbrief.rrr.bf
*********node843.detbrief.rrr.bf
**********734.detbrief.rrr.bf
**********735.detbrief.rrr.bf
*******node211.detbrief.rrr.bf
********node422.detbrief.rrr.bf
*********node844.detbrief.rrr.bf
**********736.detbrief.rrr.bf
**********737.detbrief.rrr.bf
*********node845.detbrief.rrr.bf
**********738.detbrief.rrr.bf
**********739.detbrief.rrr.bf
********node423.detbrief.rrr.bf
*********node846.detbrief.rrr.bf
**********74.detbrief.rrr.bf
**********740.detbrief.rrr.bf
*********node847.detbrief.rrr.bf
**********741.detbrief.rrr.bf
**********742.detbrief.rrr.bf
*****node53.detbrief.rrr.bf
******node106.detbrief.rrr.bf
*******node212.detbrief.rrr.bf
********node424.detbrief.rrr.bf
*********node848.detbrief.rrr.bf
**********743.detbrief.rrr.bf
**********744.detbrief.rrr.bf
*********node849.detbrief.rrr.bf
**********745.detbrief.rrr.bf
**********746.detbrief.rrr.bf
********node425.detbrief.rrr.bf
*********node850.detbrief.rrr.bf
**********747.detbrief.rrr.bf
**********748.detbrief.rrr.bf
*********node851.detbrief.rrr.bf
**********749.detbrief.rrr.bf
**********75.detbrief.rrr.bf
*******node213.detbrief.rrr.bf
********node426.detbrief.rrr.bf
*********node852.detbrief.rrr.bf
**********750.detbrief.rrr.bf
**********751.detbrief.rrr.bf
*********node853.detbrief.rrr.bf
**********752.detbrief.rrr.bf
**********753.detbrief.rrr.bf
********node427.detbrief.rrr.bf
*********node854.detbrief.rrr.bf
**********754.detbrief.rrr.bf
**********755.detbrief.rrr.bf
*********node855.detbrief.rrr.bf
**********756.detbrief.rrr.bf
**********757.detbrief.rrr.bf
******node107.detbrief.rrr.bf
*******node214.detbrief.rrr.bf
********node428.detbrief.rrr.bf
*********node856.detbrief.rrr.bf
**********758.detbrief.rrr.bf
**********759.detbrief.rrr.bf
*********node857.detbrief.rrr.bf
**********76.detbrief.rrr.bf
**********760.detbrief.rrr.bf
********node429.detbrief.rrr.bf
*********node858.detbrief.rrr.bf
**********761.detbrief.rrr.bf
**********762.detbrief.rrr.bf
*********node859.detbrief.rrr.bf
**********763.detbrief.rrr.bf
**********764.detbrief.rrr.bf
*******node215.detbrief.rrr.bf
********node430.detbrief.rrr.bf
*********node860.detbrief.rrr.bf
**********765.detbrief.rrr.bf
**********766.detbrief.rrr.bf
*********node861.detbrief.rrr.bf
**********767.detbrief.rrr.bf
**********768.detbrief.rrr.bf
********node431.detbrief.rrr.bf
*********node862.detbrief.rrr.bf
**********769.detbrief.rrr.bf
**********77.detbrief.rrr.bf
*********node863.detbrief.rrr.bf
**********770.detbrief.rrr.bf
**********771.detbrief.rrr.bf
****node27.detbrief.rrr.bf
*****node54.detbrief.rrr.bf
******node108.detbrief.rrr.bf
*******node216.detbrief.rrr.bf
********node432.detbrief.rrr.bf
*********node864.detbrief.rrr.bf
**********772.detbrief.rrr.bf
**********773.detbrief.rrr.bf
*********node865.detbrief.rrr.bf
**********774.detbrief.rrr.bf
**********775.detbrief.rrr.bf
********node433.detbrief.rrr.bf
*********node866.detbrief.rrr.bf
**********776.detbrief.rrr.bf
**********777.detbrief.rrr.bf
*********node867.detbrief.rrr.bf
**********778.detbrief.rrr.bf
**********779.detbrief.rrr.bf
*******node217.detbrief.rrr.bf
********node434.detbrief.rrr.bf
*********node868.detbrief.rrr.bf
**********78.detbrief.rrr.bf
**********780.detbrief.rrr.bf
*********node869.detbrief.rrr.bf
**********781.detbrief.rrr.bf
**********782.detbrief.rrr.bf
********node435.detbrief.rrr.bf
*********node870.detbrief.rrr.bf
**********783.detbrief.rrr.bf
**********784.detbrief.rrr.bf
*********node871.detbrief.rrr.bf
**********785.detbrief.rrr.bf
**********786.detbrief.rrr.bf
******node109.detbrief.rrr.bf
*******node218.detbrief.rrr.bf
********node436.detbrief.rrr.bf
*********node872.detbrief.rrr.bf
**********787.detbrief.rrr.bf
**********788.detbrief.rrr.bf
*********node873.detbrief.rrr.bf
**********789.detbrief.rrr.bf
**********79.detbrief.rrr.bf
********node437.detbrief.rrr.bf
*********node874.detbrief.rrr.bf
**********790.detbrief.rrr.bf
**********791.detbrief.rrr.bf
*********node875.detbrief.rrr.bf
**********792.detbrief.rrr.bf
**********793.detbrief.rrr.bf
*******node219.detbrief.rrr.bf
********node438.detbrief.rrr.bf
*********node876.detbrief.rrr.bf
**********794.detbrief.rrr.bf
**********795.detbrief.rrr.bf
*********node877.detbrief.rrr.bf
**********796.detbrief.rrr.bf
**********797.detbrief.rrr.bf
********node439.detbrief.rrr.bf
*********node878.detbrief.rrr.bf
**********798.detbrief.rrr.bf
**********799.detbrief.rrr.bf
*********node879.detbrief.rrr.bf
**********8.detbrief.rrr.bf
**********80.detbrief.rrr.bf
*****node55.detbrief.rrr.bf
******node110.detbrief.rrr.bf
*******node220.detbrief.rrr.bf
********node440.detbrief.rrr.bf
*********node880.detbrief.rrr.bf
**********800.detbrief.rrr.bf
**********801.detbrief.rrr.bf
*********node881.detbrief.rrr.bf
**********802.detbrief.rrr.bf
**********803.detbrief.rrr.bf
********node441.detbrief.rrr.bf
*********node882.detbrief.rrr.bf
**********804.detbrief.rrr.bf
**********805.detbrief.rrr.bf
*********node883.detbrief.rrr.bf
**********806.detbrief.rrr.bf
**********807.detbrief.rrr.bf
*******node221.detbrief.rrr.bf
********node442.detbrief.rrr.bf
*********node884.detbrief.rrr.bf
**********808.detbrief.rrr.bf
**********809.detbrief.rrr.bf
*********node885.detbrief.rrr.bf
**********81.detbrief.rrr.bf
**********810.detbrief.rrr.bf
********node443.detbrief.rrr.bf
*********node886.detbrief.rrr.bf
**********811.detbrief.rrr.bf
**********812.detbrief.rrr.bf
*********node887.detbrief.rrr.bf
**********813.detbrief.rrr.bf
**********814.detbrief.rrr.bf
******node111.detbrief.rrr.bf
*******node222.detbrief.rrr.bf
********node444.detbrief.rrr.bf
*********node888.detbrief.rrr.bf
**********815.detbrief.rrr.bf
**********816.detbrief.rrr.bf
*********node889.detbrief.rrr.bf
**********817.detbrief.rrr.bf
**********818.detbrief.rrr.bf
********node445.detbrief.rrr.bf
*********node890.detbrief.rrr.bf
**********819.detbrief.rrr.bf
**********82.detbrief.rrr.bf
*********node891.detbrief.rrr.bf
**********820.detbrief.rrr.bf
**********821.detbrief.rrr.bf
*******node223.detbrief.rrr.bf
********node446.detbrief.rrr.bf
*********node892.detbrief.rrr.bf
**********822.detbrief.rrr.bf
**********823.detbrief.rrr.bf
*********node893.detbrief.rrr.bf
**********824.detbrief.rrr.bf
**********825.detbrief.rrr.bf
********node447.detbrief.rrr.bf
*********node894.detbrief.rrr.bf
**********826.detbrief.rrr.bf
**********827.detbrief.rrr.bf
*********node895.detbrief.rrr.bf
**********828.detbrief.rrr.bf
**********829.detbrief.rrr.bf
**node7.detbrief.rrr.bf
***node14.detbrief.rrr.bf
****node28.detbrief.rrr.bf
*****node56.detbrief.rrr.bf
******node112.detbrief.rrr.bf
*******node224.detbrief.rrr.bf
********node448.detbrief.rrr.bf
*********node896.detbrief.rrr.bf
**********83.detbrief.rrr.bf
**********830.detbrief.rrr.bf
*********node897.detbrief.rrr.bf
**********831.detbrief.rrr.bf
**********832.detbrief.rrr.bf
********node449.detbrief.rrr.bf
*********node898.detbrief.rrr.bf
**********833.detbrief.rrr.bf
**********834.detbrief.rrr.bf
*********node899.detbrief.rrr.bf
**********835.detbrief.rrr.bf
**********836.detbrief.rrr.bf
*******node225.detbrief.rrr.bf
********node450.detbrief.rrr.bf
*********node900.detbrief.rrr.bf
**********837.detbrief.rrr.bf
**********838.detbrief.rrr.bf
*********node901.detbrief.rrr.bf
**********839.detbrief.rrr.bf
**********84.detbrief.rrr.bf
********node451.detbrief.rrr.bf
*********node902.detbrief.rrr.bf
**********840.detbrief.rrr.bf
**********841.detbrief.rrr.bf
*********node903.detbrief.rrr.bf
**********842.detbrief.rrr.bf
**********843.detbrief.rrr.bf
******node113.detbrief.rrr.bf
*******node226.detbrief.rrr.bf
********node452.detbrief.rrr.bf
*********node904.detbrief.rrr.bf
**********844.detbrief.rrr.bf
**********845.detbrief.rrr.bf
*********node905.detbrief.rrr.bf
**********846.detbrief.rrr.bf
**********847.detbrief.rrr.bf
********node453.detbrief.rrr.bf
*********node906.detbrief.rrr.bf
**********848.detbrief.rrr.bf
**********849.detbrief.rrr.bf
*********node907.detbrief.rrr.bf
**********85.detbrief.rrr.bf
**********850.detbrief.rrr.bf
*******node227.detbrief.rrr.bf
********node454.detbrief.rrr.bf
*********node908.detbrief.rrr.bf
**********851.detbrief.rrr.bf
**********852.detbrief.rrr.bf
*********node909.detbrief.rrr.bf
**********853.detbrief.rrr.bf
**********854.detbrief.rrr.bf
********node455.detbrief.rrr.bf
*********node910.detbrief.rrr.bf
**********855.detbrief.rrr.bf
**********856.detbrief.rrr.bf
*********node911.detbrief.rrr.bf
**********857.detbrief.rrr.bf
**********858.detbrief.rrr.bf
*****node57.detbrief.rrr.bf
******node114.detbrief.rrr.bf
*******node228.detbrief.rrr.bf
********node456.detbrief.rrr.bf
*********node912.detbrief.rrr.bf
**********859.detbrief.rrr.bf
**********86.detbrief.rrr.bf
*********node913.detbrief.rrr.bf
**********860.detbrief.rrr.bf
**********861.detbrief.rrr.bf
********node457.detbrief.rrr.bf
*********node914.detbrief.rrr.bf
**********862.detbrief.rrr.bf
**********863.detbrief.rrr.bf
*********node915.detbrief.rrr.bf
**********864.detbrief.rrr.bf
**********865.detbrief.rrr.bf
*******node229.detbrief.rrr.bf
********node458.detbrief.rrr.bf
*********node916.detbrief.rrr.bf
**********866.detbrief.rrr.bf
**********867.detbrief.rrr.bf
*********node917.detbrief.rrr.bf
**********868.detbrief.rrr.bf
**********869.detbrief.rrr.bf
********node459.detbrief.rrr.bf
*********node918.detbrief.rrr.bf
**********87.detbrief.rrr.bf
**********870.detbrief.rrr.bf
*********node919.detbrief.rrr.bf
**********871.detbrief.rrr.bf
**********872.detbrief.rrr.bf
******node115.detbrief.rrr.bf
*******node230.detbrief.rrr.bf
********node460.detbrief.rrr.bf
*********node920.detbrief.rrr.bf
**********873.detbrief.rrr.bf
**********874.detbrief.rrr.bf
*********node921.detbrief.rrr.bf
**********875.detbrief.rrr.bf
**********876.detbrief.rrr.bf
********node461.detbrief.rrr.bf
*********node922.detbrief.rrr.bf
**********877.detbrief.rrr.bf
**********878.detbrief.rrr.bf
*********node923.detbrief.rrr.bf
**********879.detbrief.rrr.bf
**********88.detbrief.rrr.bf
*******node231.detbrief.rrr.bf
********node462.detbrief.rrr.bf
*********node924.detbrief.rrr.bf
**********880.detbrief.rrr.bf
**********881.detbrief.rrr.bf
*********node925.detbrief.rrr.bf
**********882.detbrief.rrr.bf
**********883.detbrief.rrr.bf
********node463.detbrief.rrr.bf
*********node926.detbrief.rrr.bf
**********884.detbrief.rrr.bf
**********885.detbrief.rrr.bf
*********node927.detbrief.rrr.bf
**********886.detbrief.rrr.bf
**********887.detbrief.rrr.bf
****node29.detbrief.rrr.bf
*****node58.detbrief.rrr.bf
******node116.detbrief.rrr.bf
*******node232.detbrief.rrr.bf
********node464.detbrief.rrr.bf
*********node928.detbrief.rrr.bf
**********888.detbrief.rrr.bf
**********889.detbrief.rrr.bf
*********node929.detbrief.rrr.bf
**********89.detbrief.rrr.bf
**********890.detbrief.rrr.bf
********node465.detbrief.rrr.bf
*********node930.detbrief.rrr.bf
**********891.detbrief.rrr.bf
**********892.detbrief.rrr.bf
*********node931.detbrief.rrr.bf
**********893.detbrief.rrr.bf
**********894.detbrief.rrr.bf
*******node233.detbrief.rrr.bf
********node466.detbrief.rrr.bf
*********node932.detbrief.rrr.bf
**********895.detbrief.rrr.bf
**********896.detbrief.rrr.bf
*********node933.detbrief.rrr.bf
**********897.detbrief.rrr.bf
**********898.detbrief.rrr.bf
********node467.detbrief.rrr.bf
*********node934.detbrief.rrr.bf
**********899.detbrief.rrr.bf
**********9.detbrief.rrr.bf
*********node935.detbrief.rrr.bf
**********90.detbrief.rrr.bf
**********900.detbrief.rrr.bf
******node117.detbrief.rrr.bf
*******node234.detbrief.rrr.bf
********node468.detbrief.rrr.bf
*********node936.detbrief.rrr.bf
**********901.detbrief.rrr.bf
**********902.detbrief.rrr.bf
*********node937.detbrief.rrr.bf
**********903.detbrief.rrr.bf
**********904.detbrief.rrr.bf
********node469.detbrief.rrr.bf
*********node938.detbrief.rrr.bf
**********905.detbrief.rrr.bf
**********906.detbrief.rrr.bf
*********node939.detbrief.rrr.bf
**********907.detbrief.rrr.bf
**********908.detbrief.rrr.bf
*******node235.detbrief.rrr.bf
********node470.detbrief.rrr.bf
*********node940.detbrief.rrr.bf
**********909.detbrief.rrr.bf
**********91.detbrief.rrr.bf
*********node941.detbrief.rrr.bf
**********910.detbrief.rrr.bf
**********911.detbrief.rrr.bf
********node471.detbrief.rrr.bf
*********node942.detbrief.rrr.bf
**********912.detbrief.rrr.bf
**********913.detbrief.rrr.bf
*********node943.detbrief.rrr.bf
**********914.detbrief.rrr.bf
**********915.detbrief.rrr.bf
*****node59.detbrief.rrr.bf
******node118.detbrief.rrr.bf
*******node236.detbrief.rrr.bf
********node472.detbrief.rrr.bf
*********node944.detbrief.rrr.bf
**********916.detbrief.rrr.bf
**********917.detbrief.rrr.bf
*********node945.detbrief.rrr.bf
**********918.detbrief.rrr.bf
**********919.detbrief.rrr.bf
********node473.detbrief.rrr.bf
*********node946.detbrief.rrr.bf
**********92.detbrief.rrr.bf
**********920.detbrief.rrr.bf
*********node947.detbrief.rrr.bf
**********921.detbrief.rrr.bf
**********922.detbrief.rrr.bf
*******node237.detbrief.rrr.bf
********node474.detbrief.rrr.bf
*********node948.detbrief.rrr.bf
**********923.detbrief.rrr.bf
**********924.detbrief.rrr.bf
*********node949.detbrief.rrr.bf
**********925.detbrief.rrr.bf
**********926.detbrief.rrr.bf
********node475.detbrief.rrr.bf
*********node950.detbrief.rrr.bf
**********927.detbrief.rrr.bf
**********928.detbrief.rrr.bf
*********node951.detbrief.rrr.bf
**********929.detbrief.rrr.bf
**********93.detbrief.rrr.bf
******node119.detbrief.rrr.bf
*******node238.detbrief.rrr.bf
********node476.detbrief.rrr.bf
*********node952.detbrief.rrr.bf
**********930.detbrief.rrr.bf
**********931.detbrief.rrr.bf
*********node953.detbrief.rrr.bf
**********932.detbrief.rrr.bf
**********933.detbrief.rrr.bf
********node477.detbrief.rrr.bf
*********node954.detbrief.rrr.bf
**********934.detbrief.rrr.bf
**********935.detbrief.rrr.bf
*********node955.detbrief.rrr.bf
**********936.detbrief.rrr.bf
**********937.detbrief.rrr.bf
*******node239.detbrief.rrr.bf
********node478.detbrief.rrr.bf
*********node956.detbrief.rrr.bf
**********938.detbrief.rrr.bf
**********939.detbrief.rrr.bf
*********node957.detbrief.rrr.bf
**********94.detbrief.rrr.bf
**********940.detbrief.rrr.bf
********node479.detbrief.rrr.bf
*********node958.detbrief.rrr.bf
**********941.detbrief.rrr.bf
**********942.detbrief.rrr.bf
*********node959.detbrief.rrr.bf
**********943.detbrief.rrr.bf
**********944.detbrief.rrr.bf
***node15.detbrief.rrr.bf
****node30.detbrief.rrr.bf
*****node60.detbrief.rrr.bf
******node120.detbrief.rrr.bf
*******node240.detbrief.rrr.bf
********node480.detbrief.rrr.bf
*********node960.detbrief.rrr.bf
**********945.detbrief.rrr.bf
**********946.detbrief.rrr.bf
*********node961.detbrief.rrr.bf
**********947.detbrief.rrr.bf
**********948.detbrief.rrr.bf
********node481.detbrief.rrr.bf
*********node962.detbrief.rrr.bf
**********949.detbrief.rrr.bf
**********95.detbrief.rrr.bf
*********node963.detbrief.rrr.bf
**********950.detbrief.rrr.bf
**********951.detbrief.rrr.bf
*******node241.detbrief.rrr.bf
********node482.detbrief.rrr.bf
*********node964.detbrief.rrr.bf
**********952.detbrief.rrr.bf
**********953.detbrief.rrr.bf
*********node965.detbrief.rrr.bf
**********954.detbrief.rrr.bf
**********955.detbrief.rrr.bf
********node483.detbrief.rrr.bf
*********node966.detbrief.rrr.bf
**********956.detbrief.rrr.bf
**********957.detbrief.rrr.bf
*********node967.detbrief.rrr.bf
**********958.detbrief.rrr.bf
**********959.detbrief.rrr.bf
******node121.detbrief.rrr.bf
*******node242.detbrief.rrr.bf
********node484.detbrief.rrr.bf
*********node968.detbrief.rrr.bf
**********96.detbrief.rrr.bf
**********960.detbrief.rrr.bf
*********node969.detbrief.rrr.bf
**********961.detbrief.rrr.bf
**********962.detbrief.rrr.bf
********node485.detbrief.rrr.bf
*********node970.detbrief.rrr.bf
**********963.detbrief.rrr.bf
**********964.detbrief.rrr.bf
*********node971.detbrief.rrr.bf
**********965.detbrief.rrr.bf
**********966.detbrief.rrr.bf
*******node243.detbrief.rrr.bf
********node486.detbrief.rrr.bf
*********node972.detbrief.rrr.bf
**********967.detbrief.rrr.bf
**********968.detbrief.rrr.bf
*********node973.detbrief.rrr.bf
**********969.detbrief.rrr.bf
**********97.detbrief.rrr.bf
********node487.detbrief.rrr.bf
*********node974.detbrief.rrr.bf
**********970.detbrief.rrr.bf
**********971.detbrief.rrr.bf
*********node975.detbrief.rrr.bf
**********972.detbrief.rrr.bf
**********973.detbrief.rrr.bf
*****node61.detbrief.rrr.bf
******node122.detbrief.rrr.bf
*******node244.detbrief.rrr.bf
********node488.detbrief.rrr.bf
*********node976.detbrief.rrr.bf
**********974.detbrief.rrr.bf
**********975.detbrief.rrr.bf
*********node977.detbrief.rrr.bf
**********976.detbrief.rrr.bf
**********977.detbrief.rrr.bf
********node489.detbrief.rrr.bf
*********node978.detbrief.rrr.bf
**********978.detbrief.rrr.bf
**********979.detbrief.rrr.bf
*********node979.detbrief.rrr.bf
**********98.detbrief.rrr.bf
**********980.detbrief.rrr.bf
*******node245.detbrief.rrr.bf
********node490.detbrief.rrr.bf
*********node980.detbrief.rrr.bf
**********981.detbrief.rrr.bf
**********982.detbrief.rrr.bf
*********node981.detbrief.rrr.bf
**********983.detbrief.rrr.bf
**********984.detbrief.rrr.bf
********node491.detbrief.rrr.bf
*********node982.detbrief.rrr.bf
**********985.detbrief.rrr.bf
**********986.detbrief.rrr.bf
*********node983.detbrief.rrr.bf
**********987.detbrief.rrr.bf
**********988.detbrief.rrr.bf
******node123.detbrief.rrr.bf
*******node246.detbrief.rrr.bf
********node492.detbrief.rrr.bf
*********node984.detbrief.rrr.bf
**********989.detbrief.rrr.bf
**********99.detbrief.rrr.bf
*********node985.detbrief.rrr.bf
**********990.detbrief.rrr.bf
**********991.detbrief.rrr.bf
********node493.detbrief.rrr.bf
*********node986.detbrief.rrr.bf
**********992.detbrief.rrr.bf
**********993.detbrief.rrr.bf
*********node987.detbrief.rrr.bf
**********994.detbrief.rrr.bf
**********995.detbrief.rrr.bf
*******node247.detbrief.rrr.bf
********node494.detbrief.rrr.bf
*********node988.detbrief.rrr.bf
**********996.detbrief.rrr.bf
**********997.detbrief.rrr.bf
*********node989.detbrief.rrr.bf
**********998.detbrief.rrr.bf
**********999.detbrief.rrr.bf
********node495.detbrief.rrr.bf
*********node990.detbrief.rrr.bf
**********node1024.detbrief.rrr.bf
***********0.detbrief.rrr.bf
***********1.detbrief.rrr.bf
**********node1025.detbrief.rrr.bf
***********10.detbrief.rrr.bf
***********100.detbrief.rrr.bf
*********node991.detbrief.rrr.bf
**********node1026.detbrief.rrr.bf
***********1000.detbrief.rrr.bf
***********1001.detbrief.rrr.bf
**********node1027.detbrief.rrr.bf
***********1002.detbrief.rrr.bf
***********1003.detbrief.rrr.bf
****node31.detbrief.rrr.bf
*****node62.detbrief.rrr.bf
******node124.detbrief.rrr.bf
*******node248.detbrief.rrr.bf
********node496.detbrief.rrr.bf
*********node992.detbrief.rrr.bf
**********node1028.detbrief.rrr.bf
***********1004.detbrief.rrr.bf
***********1005.detbrief.rrr.bf
**********node1029.detbrief.rrr.bf
***********1006.detbrief.rrr.bf
***********1007.detbrief.rrr.bf
*********node993.detbrief.rrr.bf
**********node1030.detbrief.rrr.bf
***********1008.detbrief.rrr.bf
***********1009.detbrief.rrr.bf
**********node1031.detbrief.rrr.bf
***********101.detbrief.rrr.bf
***********1010.detbrief.rrr.bf
********node497.detbrief.rrr.bf
*********node994.detbrief.rrr.bf
**********node1032.detbrief.rrr.bf
***********1011.detbrief.rrr.bf
***********1012.detbrief.rrr.bf
**********node1033.detbrief.rrr.bf
***********1013.detbrief.rrr.bf
***********1014.detbrief.rrr.bf
*********node995.detbrief.rrr.bf
**********node1034.detbrief.rrr.bf
***********1015.detbrief.rrr.bf
***********1016.detbrief.rrr.bf
**********node1035.detbrief.rrr.bf
***********1017.detbrief.rrr.bf
***********1018.detbrief.rrr.bf
*******node249.detbrief.rrr.bf
********node498.detbrief.rrr.bf
*********node996.detbrief.rrr.bf
**********node1036.detbrief.rrr.bf
***********1019.detbrief.rrr.bf
***********102.detbrief.rrr.bf
**********node1037.detbrief.rrr.bf
***********1020.detbrief.rrr.bf
***********1021.detbrief.rrr.bf
*********node997.detbrief.rrr.bf
**********node1038.detbrief.rrr.bf
***********1022.detbrief.rrr.bf
***********1023.detbrief.rrr.bf
**********node1039.detbrief.rrr.bf
***********1024.detbrief.rrr.bf
***********1025.detbrief.rrr.bf
********node499.detbrief.rrr.bf
*********node998.detbrief.rrr.bf
**********node1040.detbrief.rrr.bf
***********1026.detbrief.rrr.bf
***********1027.detbrief.rrr.bf
**********node1041.detbrief.rrr.bf
***********1028.detbrief.rrr.bf
***********1029.detbrief.rrr.bf
*********node999.detbrief.rrr.bf
**********node1042.detbrief.rrr.bf
***********103.detbrief.rrr.bf
***********1030.detbrief.rrr.bf
**********node1043.detbrief.rrr.bf
***********1031.detbrief.rrr.bf
***********1032.detbrief.rrr.bf
******node125.detbrief.rrr.bf
*******node250.detbrief.rrr.bf
********node500.detbrief.rrr.bf
*********node1000.detbrief.rrr.bf
**********node1044.detbrief.rrr.bf
***********1033.detbrief.rrr.bf
***********1034.detbrief.rrr.bf
**********node1045.detbrief.rrr.bf
***********1035.detbrief.rrr.bf
***********1036.detbrief.rrr.bf
*********node1001.detbrief.rrr.bf
**********node1046.detbrief.rrr.bf
***********1037.detbrief.rrr.bf
***********1038.detbrief.rrr.bf
**********node1047.detbrief.rrr.bf
***********1039.detbrief.rrr.bf
***********104.detbrief.rrr.bf
********node501.detbrief.rrr.bf
*********node1002.detbrief.rrr.bf
**********node1048.detbrief.rrr.bf
***********1040.detbrief.rrr.bf
***********1041.detbrief.rrr.bf
**********node1049.detbrief.rrr.bf
***********1042.detbrief.rrr.bf
***********1043.detbrief.rrr.bf
*********node1003.detbrief.rrr.bf
**********node1050.detbrief.rrr.bf
***********1044.detbrief.rrr.bf
***********1045.detbrief.rrr.bf
**********node1051.detbrief.rrr.bf
***********1046.detbrief.rrr.bf
***********1047.detbrief.rrr.bf
*******node251.detbrief.rrr.bf
********node502.detbrief.rrr.bf
*********node1004.detbrief.rrr.bf
**********node1052.detbrief.rrr.bf
***********1048.detbrief.rrr.bf
***********1049.detbrief.rrr.bf
**********node1053.detbrief.rrr.bf
***********105.detbrief.rrr.bf
***********1050.detbrief.rrr.bf
*********node1005.detbrief.rrr.bf
**********node1054.detbrief.rrr.bf
***********1051.detbrief.rrr.bf
***********1052.detbrief.rrr.bf
**********node1055.detbrief.rrr.bf
***********1053.detbrief.rrr.bf
***********1054.detbrief.rrr.bf
********node503.detbrief.rrr.bf
*********node1006.detbrief.rrr.bf
**********node1056.detbrief.rrr.bf
***********1055.detbrief.rrr.bf
***********1056.detbrief.rrr.bf
**********node1057.detbrief.rrr.bf
***********1057.detbrief.rrr.bf
***********1058.detbrief.rrr.bf
*********node1007.detbrief.rrr.bf
**********node1058.detbrief.rrr.bf
***********1059.detbrief.rrr.bf
***********106.detbrief.rrr.bf
**********node1059.detbrief.rrr.bf
***********1060.detbrief.rrr.bf
***********1061.detbrief.rrr.bf
*****node63.detbrief.rrr.bf
******node126.detbrief.rrr.bf
*******node252.detbrief.rrr.bf
********node504.detbrief.rrr.bf
*********node1008.detbrief.rrr.bf
**********node1060.detbrief.rrr.bf
***********1062.detbrief.rrr.bf
***********1063.detbrief.rrr.bf
**********node1061.detbrief.rrr.bf
***********1064.detbrief.rrr.bf
***********1065.detbrief.rrr.bf
*********node1009.detbrief.rrr.bf
**********node1062.detbrief.rrr.bf
***********1066.detbrief.rrr.bf
***********1067.detbrief.rrr.bf
**********node1063.detbrief.rrr.bf
***********1068.detbrief.rrr.bf
***********1069.detbrief.rrr.bf
********node505.detbrief.rrr.bf
*********node1010.detbrief.rrr.bf
**********node1064.detbrief.rrr.bf
***********107.detbrief.rrr.bf
***********1070.detbrief.rrr.bf
**********node1065.detbrief.rrr.bf
***********1071.detbrief.rrr.bf
***********1072.detbrief.rrr.bf
*********node1011.detbrief.rrr.bf
**********node1066.detbrief.rrr.bf
***********1073.detbrief.rrr.bf
***********1074.detbrief.rrr.bf
**********node1067.detbrief.rrr.bf
***********1075.detbrief.rrr.bf
***********1076.detbrief.rrr.bf
*******node253.detbrief.rrr.bf
********node506.detbrief.rrr.bf
*********node1012.detbrief.rrr.bf
**********node1068.detbrief.rrr.bf
***********1077.detbrief.rrr.bf
***********1078.detbrief.rrr.bf
**********node1069.detbrief.rrr.bf
***********1079.detbrief.rrr.bf
***********108.detbrief.rrr.bf
*********node1013.detbrief.rrr.bf
**********node1070.detbrief.rrr.bf
***********1080.detbrief.rrr.bf
***********1081.detbrief.rrr.bf
**********node1071.detbrief.rrr.bf
***********1082.detbrief.rrr.bf
***********1083.detbrief.rrr.bf
********node507.detbrief.rrr.bf
*********node1014.detbrief.rrr.bf
**********node1072.detbrief.rrr.bf
***********1084.detbrief.rrr.bf
***********1085.detbrief.rrr.bf
**********node1073.detbrief.rrr.bf
***********1086.detbrief.rrr.bf
***********1087.detbrief.rrr.bf
*********node1015.detbrief.rrr.bf
**********node1074.detbrief.rrr.bf
***********1088.detbrief.rrr.bf
***********1089.detbrief.rrr.bf
**********node1075.detbrief.rrr.bf
***********109.detbrief.rrr.bf
***********1090.detbrief.rrr.bf
******node127.detbrief.rrr.bf
*******node254.detbrief.rrr.bf
********node508.detbrief.rrr.bf
*********node1016.detbrief.rrr.bf
**********node1076.detbrief.rrr.bf
***********1091.detbrief.rrr.bf
***********11.detbrief.rrr.bf
**********node1077.detbrief.rrr.bf
***********110.detbrief.rrr.bf
***********111.detbrief.rrr.bf
*********node1017.detbrief.rrr.bf
**********node1078.detbrief.rrr.bf
***********112.detbrief.rrr.bf
***********113.detbrief.rrr.bf
**********node1079.detbrief.rrr.bf
***********114.detbrief.rrr.bf
***********115.detbrief.rrr.bf
********node509.detbrief.rrr.bf
*********node1018.detbrief.rrr.bf
**********node1080.detbrief.rrr.bf
***********116.detbrief.rrr.bf
***********117.detbrief.rrr.bf
**********node1081.detbrief.rrr.bf
***********118.detbrief.rrr.bf
***********119.detbrief.rrr.bf
*********node1019.detbrief.rrr.bf
**********node1082.detbrief.rrr.bf
***********12.detbrief.rrr.bf
***********120.detbrief.rrr.bf
**********node1083.detbrief.rrr.bf
***********121.detbrief.rrr.bf
***********122.detbrief.rrr.bf
*******node255.detbrief.rrr.bf
********node510.detbrief.rrr.bf
*********node1020.detbrief.rrr.bf
**********node1084.detbrief.rrr.bf
***********123.detbrief.rrr.bf
***********124.detbrief.rrr.bf
**********node1085.detbrief.rrr.bf
***********125.detbrief.rrr.bf
***********126.detbrief.rrr.bf
*********node1021.detbrief.rrr.bf
**********node1086.detbrief.rrr.bf
***********127.detbrief.rrr.bf
***********128.detbrief.rrr.bf
**********node1087.detbrief.rrr.bf
***********129.detbrief.rrr.bf
***********13.detbrief.rrr.bf
********node511.detbrief.rrr.bf
*********node1022.detbrief.rrr.bf
**********node1088.detbrief.rrr.bf
***********130.detbrief.rrr.bf
***********131.detbrief.rrr.bf
**********node1089.detbrief.rrr.bf
***********132.detbrief.rrr.bf
***********133.detbrief.rrr.bf
*********node1023.detbrief.rrr.bf
**********node1090.detbrief.rrr.bf
***********134.detbrief.rrr.bf
***********135.detbrief.rrr.bf
**********node1091.detbrief.rrr.bf
***********136.detbrief.rrr.bf
***********137.detbrief.rrr.bf
