node1.detbrief.rrr.bf
*node2.detbrief.rrr.bf
**node4.detbrief.rrr.bf
***node8.detbrief.rrr.bf
****4.detbrief.rrr.bf
****5.detbrief.rrr.bf
***node9.detbrief.rrr.bf
****6.detbrief.rrr.bf
****7.detbrief.rrr.bf
**node5.detbrief.rrr.bf
***node10.detbrief.rrr.bf
****8.detbrief.rrr.bf
****9.detbrief.rrr.bf
***node11.detbrief.rrr.bf
****node16.detbrief.rrr.bf
*****0.detbrief.rrr.bf
*****1.detbrief.rrr.bf
****node17.detbrief.rrr.bf
*****10.detbrief.rrr.bf
*****11.detbrief.rrr.bf
*node3.detbrief.rrr.bf
**node6.detbrief.rrr.bf
***node12.detbrief.rrr.bf
****node18.detbrief.rrr.bf
*****12.detbrief.rrr.bf
*****13.detbrief.rrr.bf
****node19.detbrief.rrr.bf
*****14.detbrief.rrr.bf
*****15.detbrief.rrr.bf
***node13.detbrief.rrr.bf
****node20.detbrief.rrr.bf
*****16.detbrief.rrr.bf
*****17.detbrief.rrr.bf
****node21.detbrief.rrr.bf
*****18.detbrief.rrr.bf
*****19.detbrief.rrr.bf
**node7.detbrief.rrr.bf
***node14.detbrief.rrr.bf
****node22.detbrief.rrr.bf
*****2.detbrief.rrr.bf
*****20.detbrief.rrr.bf
****node23.detbrief.rrr.bf
*****21.detbrief.rrr.bf
*****22.detbrief.rrr.bf
***node15.detbrief.rrr.bf
****node24.detbrief.rrr.bf
*****23.detbrief.rrr.bf
*****24.detbrief.rrr.bf
****node25.detbrief.rrr.bf
*****25.detbrief.rrr.bf
*****3.detbrief.rrr.bf
