---
title: "Analyse and compare 2WMT with SigClust"
author: "Hui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)

```

# Staphopia
```{r read staph, echo=FALSE, include=FALSE}
source("C://DataCopied/Research/R/staphFunctions.R")
path<-"C://DataCopied/Research/tree/data/staphopia-contigs"
w<-read.csv(paste(path,"/sample-k9-w100-s5-global_sim.txt",sep=""))
water<-waterStaph(paste(path,"/sample_needle.txt",sep=""),
                  paste(path,"/sample_meta.csv",sep=""))


# dt<-read.csv(paste(path,"/sample-k9-w100-s5-s100-l59.txt",sep=""),header=FALSE)
dt<-read.csv(paste(path,"/sample-k9-w100-s5-s90-l58.txt",sep=""),header=FALSE)
colnames(dt)<-c("seqID","cluster")
# cluQ_2WMT<-cluQualityStaph(dt,water)
# cluQ_2WMT<-cluQuality(dt,w,3,FALSE)
cluQ_2WMT<-cluQuality(dt,water,2,FALSE,w,3)

# avg<- cluQ_2WMT %>% summarise(across(everything(), list(mean)))

sigClust<-read.csv(paste(path,"/sigClust-k9-c",nrow(cluQ_2WMT),".txt",sep=""),header=FALSE)
# sigClust<-read.csv(paste(path,"/sigClust.txt",sep=""),header=FALSE)
colnames(sigClust)<-c("seqID","cluster")
# cluQ_sigClust<-cluQualityStaph(sigClust,water,FALSE)
# cluQ_sigClust<-cluQuality(sigClust,w,3,FALSE)
cluQ_sigClust<-cluQuality(sigClust,water,2,FALSE,w,3)

```

## Plots
```{r plot}
plotTwo(cluQ_2WMT,cluQ_sigClust,3)

# avg_sim is normalised by the max cluster size
plotTwo(normSize(cluQ_2WMT),normSize(cluQ_sigClust),ncol(cluQ_2WMT)+1)

```

```{r echo=FALSE}
# plotTwo(normSize(cluQ_2WMT,'avg_sim_sig'),normSize(cluQ_sigClust,'avg_sim_sig'),ncol(cluQ_2WMT)+1)

# plotStaph(cluQ_2WMT)

```

## AVG
```{r echo=FALSE, results='asis'}
avg<-sumAll(cluQ_2WMT,cluQ_sigClust)
kable(avg)
```


## The near neighbour of the outliers in the largest cluster 
```{r echo=FALSE, results='asis'}
# find nearest neighbours of the outliers
outliers_NN<-function(sim,var, col_i="i", col_j="j"){
  getSubsetBySize<-function(dt,summ,size=-1){
    if (size==-1){
      (dt%>%filter(cluster==(summ%>%slice(which.max(size)))$cluster[1]))$seqID
    }else{
      (dt%>%filter(cluster==(summ%>%slice(which(.data$size == size)))$cluster[1]))$seqID

    }
  }
  t_s<-getSubsetBySize(sigClust,cluQ_sigClust)
  t_w<-getSubsetBySize(dt,cluQ_2WMT)
  outliers<-setdiff(t_w,t_s)

  t<-sim%>%filter(.data[[col_i]] %in% outliers)
  outliers_best_inter<-t%>%filter(.data[[col_j]] %in% t_s)%>%
    group_by(.data[[col_i]])%>%
    slice(which(min(.data[[var]])<100))
  if (nrow(outliers_best_inter)>0){
    names(outliers_best_inter)[names(outliers_best_inter) == col_j] <- paste("best_inter_",col_j,sep="")
    names(outliers_best_inter)[names(outliers_best_inter) == var] <- paste("best_inter_",var,sep="")
    # colnames(outliers_best_inter)[2:3]<-c("inter_j",paste("best_inter_",var,sep=""))

    true_outliers<-outliers_best_inter%>%pull(col_i)
#
    NN<-t%>%filter(.data[[col_i]] %in% true_outliers & !.data[[col_j]] %in% t_w)%>%
      group_by(.data[[col_i]])%>%
      slice(which(max(.data[[var]])==.data[[var]]))
    names(NN)[names(NN) == var] <- paste("best_intra_",var,sep="")
    # colnames(NN)[which(colnames(NN)==var)]<-paste("best_intra_",var,sep="")

    NN<-merge(NN,dt,by.x=col_j,by.y="seqID")
    NN<-merge(distinct(NN,.data[[col_i]],cluster,.keep_all = TRUE),outliers_best_inter,by=col_i)
    NN<-merge(NN,cluQ_2WMT)
    NN[!grepl('\\.[x|y]$', colnames(NN))]
  }else{
    print("no outliers based on 2WMT signature")
    NULL
  }
}

NN<-outliers_NN(w,"similarity")
# N2<-outliers_NN(water,"identity.","seqID.x","seqID.y")
N2<-outliers_NN(water,"identity.")

kable(NN,caption='Jaccard of the minimisers set:')
kable(N2,caption='Smith Waterman :')
```

<!-- # Staphopia: sample-all -->
<!-- ```{r read staph, echo=FALSE, include=FALSE} -->
<!-- source("C://DataCopied/Research/R/staphFunctions.R") -->
<!-- path<-"C://DataCopied/Research/tree/data/staphopia-contigs/sample-all" -->
<!-- w<-read.csv(paste(path,"/sample-all-k9-all_sim.txt",sep="")) -->

<!-- ``` -->
<!-- ## Plot -->
<!-- ```{r read staph, echo=FALSE, include=FALSE} -->
<!-- ggplot(w)+geom_density(aes(x=similarity)) -->
<!-- ``` -->

<!-- # dt<-read.csv(paste(path,"/sample-k9-w100-s5-s100-l59.txt",sep=""),header=FALSE) -->
<!-- dt<-read.csv(paste(path,"/sample-all-k9-w100-s5-s90-l58.txt",sep=""),header=FALSE) -->
<!-- colnames(dt)<-c("seqID","cluster") -->
<!-- # cluQ_2WMT<-cluQualityStaph(dt,water) -->
<!-- # cluQ_2WMT<-cluQuality(dt,w,3,FALSE) -->
<!-- cluQ_2WMT<-cluQuality(dt,water,2,FALSE,w,3) -->
<!-- ``` -->

<!-- # avg<- cluQ_2WMT %>% summarise(across(everything(), list(mean))) -->

<!-- sigClust<-read.csv(paste(path,"/sigClust-k9-c",nrow(cluQ_2WMT),".txt",sep=""),header=FALSE) -->
<!-- # sigClust<-read.csv(paste(path,"/sigClust.txt",sep=""),header=FALSE) -->
<!-- colnames(sigClust)<-c("seqID","cluster") -->
<!-- # cluQ_sigClust<-cluQualityStaph(sigClust,water,FALSE) -->
<!-- # cluQ_sigClust<-cluQuality(sigClust,w,3,FALSE) -->
<!-- cluQ_sigClust<-cluQuality(sigClust,water,2,FALSE,w,3) -->

# Toy
```{r echo=FALSE, include=FALSE}
source("C://DataCopied/Research/R/toyFunctions.R")
dt<-plotEnt(paste(path,"/toy-k9-w100-s5-s80-l18.txt",sep=""))
cluQ_2WMT<-cluQuality(dt,water,4,FALSE)

sigClust<-plotEnt(paste(path,"/sigClust-k9-c",nrow(cluQ_2WMT),".txt",sep=""))
cluQ_sigClust<-cluQuality(sigClust,water,4,FALSE)
```


```{r echo=FALSE, include=FALSE}
dt<-plotEnt(paste(path,"/toy-k9-w100-s5-s80-l18.txt",sep=""))
print(length(unique(dt$cluster)))
```

## AVG
```{r echo=FALSE, results='asis'}
avg<-sumAll(cluQ_2WMT,cluQ_sigClust)
kable(avg)
```

## Plot
```{r echo=FALSE}
ggplot(cluQ_2WMT)+
  geom_point(aes(x=clu,y=avg_sim,size=size))+
    # geom_point(aes(x=clu,y=avg_nodeDistance,size=size))+
    ylim(50,100)
```

```{r}
plotTwo(cluQ_2WMT,cluQ_sigClust,3)
plotTwo(normSize(cluQ_2WMT),normSize(cluQ_sigClust),ncol(cluQ_2WMT)+1)
plotStaph(cluQ_2WMT,TRUE,3:2)
plotStaph(cluQ_sigClust,TRUE,3:2)
```


